# Generated by Django 4.1 on 2022-09-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to='pacientes/'),
        ),
    ]
