# Generated by Django 4.1 on 2022-09-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_health', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadospacientes',
            old_name='percentural_gordura',
            new_name='percentual_gordura',
        ),
        migrations.RenameField(
            model_name='dadospacientes',
            old_name='percentural_musclo',
            new_name='percentual_musculo',
        ),
    ]
