# Generated by Django 4.1 on 2022-09-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_health', '0003_dadospaciente_opcao_refeicao_alter_pacientes_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/<django.db.models.fields.CharField>/'),
        ),
    ]
