# Generated by Django 4.1 on 2022-09-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_health', '0004_pacientes_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='imagem',
            new_name='foto_perfil',
        ),
    ]
